# Generated by Django 5.2.7 on 2025-11-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_due_day',
            field=models.IntegerField(default=1),
        ),
    ]
