# Generated by Django 5.2.7 on 2025-11-16 12:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_account_transaction_raw_row_data_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='payment_due_day',
        ),
        migrations.AddField(
            model_name='loan',
            name='installments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10)),
                ('linked_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='transactions.loan')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
